global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - prometheus:9090

  # - job_name: login_monitoring
  #   honor_timestamps: true
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /bm_auth/login_metrics
  #   scheme: http
  #   static_configs:
  #     - targets:
  #         - prometheus_login:3030        

  # - job_name: quotation_monitoring
  #   honor_timestamps: true
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /report/monitoring/traffic_monitoring
  #   scheme: http
  #   static_configs:
  #     - targets:
  #         - bemanager-quotes:8000      

  - job_name: clients_monitoring
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /clients/metrics/metrics
    scheme: http
    static_configs:
      - targets:
          - web:8989


  
  