# Generated by Django 4.2.6 on 2023-10-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
